assistant_register/urls.py
from django.urls import path, register_converter
from . import views
from .path_converter import DateConverter


register_converter(DateConverter, 'date')

app_name = 'assistant_register'
urlpatterns = [
    path('', views.index, name='index'),
    path('doctors/', views.doctors, name='doctors'),
    path('doctor/<int:doctor_id>/', views.doctor, name='doctor'),
    path('new_doctor/', views.new_doctor, name='new_doctor'),
    path('entry_day/<int:doctor_id>/<date:date>/', views.entry_day, name='entry_day'),
    path('entry/<int:doctor_id>/<date:date>/<int:hour>', views.entry, name='entry'),
    path('patients/', views.patients, name='patients'),
    path('new_patient/', views.new_patient, name='new_patient'),
    path('profit_of_month/', views.profit_of_month, name='profit_of_month')
]

assistant_registrar/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from assistant_registrar import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('assistant_register.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

assistant_register/models.py
from django.db import models


class Doctor(models.Model):
    categories = [
        (None, 'Category not selected'),
        (1, 'First'),
        (2, 'Second'),
        (3, 'Third'),
    ]

    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    category = models.PositiveSmallIntegerField(("category"), choices=categories)
    photo = models.ImageField(upload_to="photos/%Y/%m/%d")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Patient(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    polis = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.first_name} {self.last_name}, Polis {self.polis}"


class Entry(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.SET_NULL, blank=True, null=True)
    date_time = models.DateTimeField()
    price = models.DecimalField(max_digits=20, decimal_places=2)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        return f"Запись на {self.date_time} с ценой {self.price}"

assistant_register/forms.py
from django import forms
from .models import Doctor, Patient, Entry


class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = ['first_name', 'last_name', 'category', 'photo']
        labels = {'first_name': 'First name', 'last_name': 'Last name', 'category': 'Category', 'photo': 'Photo'}


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['first_name', 'last_name', 'polis']
        labels = {'first_name': 'First name', 'last_name': 'Last name', 'Polis': 'polis'}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['patient', 'price']
        labels = {'patient': 'Patient', 'price': 'Price'}


class Profit_of_month(forms.Form):
    doctor = forms.ModelChoiceField(queryset=Doctor.objects.all(), empty_label='All doctors', required=False)

assistant_register/views.py
import calendar
from datetime import datetime, time
from django.db.models.functions import TruncDate
from django.db.models import Count
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Doctor, Patient, Entry
from .forms import DoctorForm, EntryForm, PatientForm, Profit_of_month


def index(request):
    return render(request, 'assistant_register/index.html')


def doctors(request):
    doctors = Doctor.objects.order_by('category')
    context = {'doctors': doctors}

    return render(request, 'assistant_register/doctors.html', context=context)


def doctor(request, doctor_id):
    today = datetime.now()
    today_year, today_month = today.year, today.month
    start_date = today.replace(day=1, hour=0, minute=0, second=0)
    end_date = today.replace(day=calendar.monthrange(today_year, today_month)[1], hour=0, minute=0, second=0)

    doctor = Doctor.objects.get(id=doctor_id)
    entries = (doctor.entry_set.annotate(date=TruncDate('date_time'))
               .filter(date_time__range=(start_date, end_date))
               .values('date')
               .annotate(count=Count('date'))
               .order_by())

    entries = [i['date'] for i in entries if i['count'] == 4]
    lst_days = []

    obj = calendar.Calendar()
    temp_lst = list(obj.itermonthdates(today_year, today_month))

    for i in temp_lst:
        # -1 выходные 0 занято none свободно
        if i.month != today_month:
            flag = -1
        elif datetime.weekday(i) in (5, 6):
            flag = -1
        elif i in entries:
            flag = 0
        else:
            flag = None

        lst_days.append({'date': i, 'flag': flag})

    lst_days = [lst_days[i:i + 7] for i in range(0, len(lst_days), 7)]

    context = {'doctor': doctor, 'entries': entries, 'lst_days': lst_days}
    return render(request, 'assistant_register/doctor.html', context=context)


@login_required
def new_doctor(request):
    if request.method != 'POST':
        form = DoctorForm()
    else:
        form = DoctorForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('assistant_register:doctors')

    context = {'form': form}
    return render(request, 'assistant_register/new_doctor.html', context)


@login_required
def entry_day(request, doctor_id, date):
    doctor = Doctor.objects.get(id=doctor_id)
    entries = (doctor.entry_set.annotate(date=TruncDate('date_time'))
               .values('date_time')
               .filter(date=date))

    entries = [time(i['date_time'].hour) for i in entries]
    temp_lst = [time(hour=i) for i in range(8, 12)]
    lst_times = []

    for i in temp_lst:
        flag = None
        if i in entries:
            flag = 0

        lst_times.append({'time': i, 'hour': i.hour, 'flag': flag})

    context = {'doctor': doctor, 'date': date, 'lst_times': lst_times}
    return render(request, 'assistant_register/entry_day.html', context=context)


@login_required
def entry(request, doctor_id, date, hour):
    doctor = Doctor.objects.get(id=doctor_id)
    today = datetime.combine(date, time(hour))
    entry = Entry.objects.filter(date_time=today, doctor_id=doctor_id)

    if len(entry) == 0:
        if request.method != 'POST':
            form = EntryForm()
        else:
            form = EntryForm(data=request.POST, files=request.FILES)
            if form.is_valid():
                new_entry = form.save(commit=False)

                if doctor.category == 2:
                    new_entry.price = float(new_entry.price) * 1.5
                elif doctor.category == 1:
                    new_entry.price = float(new_entry.price) * 2
                new_entry.doctor = doctor
                new_entry.date_time = today
                new_entry.save()
                return redirect('assistant_register:entry_day', doctor.id, date)
    else:
        if request.method != 'POST':
            form = EntryForm(instance=entry[0])
        else:
            form = EntryForm(instance=entry[0], data=request.POST, files=request.FILES)
            if form.is_valid():
                form.save()
                return redirect('assistant_register:entry_day', doctor.id, date)

    context = {'doctor': doctor, 'date': date, 'hour': hour, 'form': form}
    return render(request, 'assistant_register/entry.html', context=context)


@login_required
def patients(request):
    patients = Patient.objects.order_by('last_name', 'first_name')
    context = {'patients': patients}

    return render(request, 'assistant_register/patients.html', context=context)


@login_required
def new_patient(request):
    if request.method != 'POST':
        form = PatientForm()
    else:
        form = PatientForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('assistant_register:patients')

    context = {'form': form}
    return render(request, 'assistant_register/new_patient.html', context)

@login_required
def profit_of_month(request):
    today = datetime.now()
    start_date = today.replace(day=1, hour=0, minute=0, second=0)

    if request.method != 'POST':
        form = Profit_of_month()
    else:
        form = Profit_of_month(data=request.POST, files=request.FILES)
        doctor_id = request.POST['doctor']
        if form.is_valid():
            if doctor_id:
                doctor = Doctor.objects.get(id=doctor_id)
                entries = (doctor.entry_set.annotate(date=TruncDate('date_time'))
                           .filter(date_time__range=(start_date, today))
                           .values('price'))
            else:
                doctor = "All doctors"
                entries = (Entry.objects.annotate(date=TruncDate('date_time'))
                           .filter(date_time__range=(start_date, today))
                           .values('price'))

            finish_summ = 0
            for i in entries:
                finish_summ += float(i['price'])


            context = {'doctor': doctor, 'finish_summ': finish_summ}
            return render(request, 'assistant_register/finish_summ.html', context)

    context = {'form': form}
    return render(request, 'assistant_register/profit_of_month.html', context)

assistant_register/templates/assistant_register/base.html
{% load bootstrap4 %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" ,
          initial-scale=1.0,
          shrink-to-fit="no"
    >
    <title>Assistant register</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
<style type="text/css">
    .btn-xl {
        width: 150px;
        height: 100px;
        padding: 25px 15px;
        font-size: 20px;
        border-radius: 10px;
    }
</style>
<nav class="navbar navbar-expand-md navbar-light mb-4 border"
     style="background-color: #F7CBCB;">
    <a class="navbar-brand" href="{% url 'assistant_register:index' %}">Assistant register</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto border border-danger rounded-sm">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'assistant_register:doctors' %}">Doctors</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'assistant_register:patients' %}">Patients</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'assistant_register:profit_of_month' %}">Profit of month</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
            {% endif %}
        </ul>
    </div>

</nav>
<main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</main>
</body>
</html>

assistant_register/templates/assistant_register/doctor.html
{% extends 'assistant_register/base.html' %}


{% load bootstrap4 %}

{% block page_header %}
    <h2>Doctor: {{ doctor }}</h2>
{% endblock page_header %}


{% block content %}

    {% if doctor.photo %}
        <p><img src="{{ doctor.photo.url }}" class="img-fluid rounded float-start"
                width="200" height="200"></p>
    {% endif %}
    <h3>Days:</h3>

    <ul>
        {% for week in lst_days %}
            <div class="btn-group btn-group-lg" role="group" aria-label="Basic example">
                {% for day in week %}
                    {% if day.flag == None %}
                        <h3><a class="btn btn-primary btn-xl"
                               href="{% url 'assistant_register:entry_day' doctor.id day.date %}"
                               role="button">{{ day.date }}</a></h3>
                    {% elif day.flag == 0 %}
                        <h3><a class="btn btn-secondary btn-xl"
                               href="{% url 'assistant_register:entry_day' doctor.id day.date %}"
                               role="button">{{ day.date }}</a></h3>
                    {% elif day.flag == -1 %}
                        <h3><a class="btn btn-lg btn-warning btn-xl"
                               role="button">{{ day.date }}</a></h3>
                    {% endif %}
            {% endfor %}
            </div>
        {% empty %}
            <li>There are no entries for this topic yet.</li>
        {% endfor %}
    </ul>

{% endblock content %}

assistant_register/templates/assistant_register/doctors.html
{% extends "assistant_register/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h1>Doctors</h1>
{% endblock page_header %}

{% block content %}

    <ul>
        {% for doctor in doctors %}
            <li>
                <h3>
                    <a href="{% url 'assistant_register:doctor' doctor.id %}">{{ doctor }}</a>
                </h3>
            </li>
        {% empty %}
            <li><h3>No doctor have been added yet.</h3></li>
        {% endfor %}
    </ul>
    <h3><a class="btn btn-lg btn-primary"
           href="{% url 'assistant_register:new_doctor' %}"
           role="button">Add a new doctor</a></h3>

{% endblock content %}

assistant_register/templates/assistant_register/entry.html
{% extends "assistant_register/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h3><a href="{% url 'assistant_register:doctor' doctor.id %}">Doctor: {{ doctor }}</a></h3>
    <h3><a href="{% url 'assistant_register:entry_day' doctor.id date %}">Date: {{ date }}</a></h3>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'assistant_register:entry' doctor.id date hour %}" class="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Add entry</button>
        {% endbuttons %}
    </form>

{% endblock content %}

assistant_register/templates/assistant_register/entry_day.html
{% extends 'assistant_register/base.html' %}


{% load bootstrap4 %}

{% block page_header %}
    <h2><a href="{% url 'assistant_register:doctor' doctor.id %}">{{ doctor }}</a></h2>
{% endblock page_header %}


{% block content %}

    <h3>Date: {{ date }}</h3>
    <h3>Entries:</h3>

    <ul>
        {% for time in lst_times %}
            {% if time.flag == None %}
                <h3><a class="btn btn-lg btn-primary"
                       href="{% url 'assistant_register:entry' doctor.id date time.hour %}"
                       role="button">{{ time.time }}</a></h3>
            {% elif time.flag == 0 %}
                <h3><a class="btn btn-lg btn-secondary"
                       href="{% url 'assistant_register:entry' doctor.id date time.hour %}"
                       role="button">{{ time.time }}</a></h3>
            {% elif time.flag == -1 %}
                <h3><a class="btn btn-lg btn-warning"
                       role="button">{{ time.time }}</a></h3>
            {% endif %}
        {% empty %}
            <li>There are no entries for this topic yet.</li>
        {% endfor %}
    </ul>

{% endblock content %}

assistant_register/templates/assistant_register/finish_summ.html
{% extends "assistant_register/base.html" %}


{% block content %}
    <h3>Doctor: {{ doctor }}</h3>

    <p>Your profit today is - {{ finish_summ }}</p>
{% endblock content %}

assistant_register/templates/assistant_register/index.html
{% extends "assistant_register/base.html" %}

{% block page_header %}

    <div class='jumbotron' style="background-color: #FDE5E5;">
        <h1 class="display-3">Start looking for a new job here.!!!!!!!!!</h1>

        <div class="lead">
            <p>The more difficult the job, the easier it is to get a job.!!!!!!!!!1</p>
            <p>This service will help you find a job or offer you suitable workers.!!!!!!!!</p>
        </div>

        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
           role="button">Register &raquo;
        </a>
    </div>

{% endblock page_header %}

assistant_register/templates/assistant_register/new_doctor.html
{% extends "assistant_register/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Add a new doctor:</h2>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'assistant_register:new_doctor' %}" class="form" method="post"
          enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Add doctor</button>
        {% endbuttons %}
    </form>

{% endblock content %}

assistant_register/templates/assistant_register/new_patient.html
{% extends "assistant_register/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Add a new patient:</h2>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'assistant_register:new_patient' %}" class="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Add patient</button>
        {% endbuttons %}
    </form>

{% endblock content %}

assistant_register/templates/assistant_register/patients.html
{% extends "assistant_register/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h1>Patients</h1>
{% endblock page_header %}

{% block content %}

    <ul>
        {% for patient in patients %}
            <li>
                <h3>
                    <p>{{ patient }}</p>
                </h3>
            </li>
        {% empty %}
            <li><h3>No patient have been added yet.</h3></li>
        {% endfor %}
    </ul>
    <h3><a class="btn btn-lg btn-primary"
           href="{% url 'assistant_register:new_patient' %}"
           role="button">Add a new patient</a></h3>

{% endblock content %}

assistant_register/templates/assistant_register/profit_of_month.html
{% extends "assistant_register/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Profit of month</h2>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'assistant_register:profit_of_month' %}" class="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Get profit</button>
        {% endbuttons %}
    </form>

{% endblock content %}